'use client';
import { useState, useEffect } from 'react';
import {
  X, ChevronLeft, ChevronRight, Maximize2, Minimize2,
  TrendingUp, BarChart3, PieChart, Sparkles, CheckCircle, ShieldCheck
} from 'lucide-react';

interface SlideDeckModalProps {
  open: boolean;
  onClose: () => void;
  reportId: string;
  reportTitle?: string;
  clientName?: string;
}

export default function SlideDeckModal({ open, onClose, reportId, reportTitle, clientName }: SlideDeckModalProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [deckData, setDeckData] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (open && reportId) {
      setCurrentSlide(0);
      fetchSlideData();
    }
  }, [open, reportId]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!open) return;
      if (e.key === 'ArrowRight' || e.key === 'Space') {
        setCurrentSlide((prev) => (deckData && prev < deckData.slides.length - 1 ? prev + 1 : prev));
      } else if (e.key === 'ArrowLeft') {
        setCurrentSlide((prev) => (prev > 0 ? prev - 1 : 0));
      } else if (e.key === 'Escape') {
        if (isFullscreen) setIsFullscreen(false);
        else onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [open, deckData, isFullscreen]);

  const fetchSlideData = async () => {
    setLoading(true);
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
      const token = typeof window !== 'undefined' ? localStorage.getItem('riq_token') : '';
      const res = await fetch(`${apiUrl}/api/reports/${reportId}/slides`, {
        headers: { Authorization: `Bearer ${token || ''}` }
      });
      if (res.ok) {
        setDeckData(await res.json());
      } else {
        // Fallback slides
        setDeckData({
          title: reportTitle || 'Client Performance Presentation',
          clientName: clientName || 'Acme Corp',
          agencyName: 'ReportIQ Partner Agency',
          period: 'Current Reporting Period',
          slides: [
            {
              slideNumber: 1,
              type: 'cover',
              title: reportTitle || 'Performance & Growth Strategy Review',
              subtitle: `Prepared for ${clientName || 'Valued Client'}`,
              badge: 'Executive Review Deck',
              highlight: 'Monthly Digital Acquisition & Revenue Attribution'
            },
            {
              slideNumber: 2,
              type: 'metrics',
              title: 'Executive KPI Performance',
              subtitle: 'Core digital growth indicators vs baseline targets',
              metrics: [
                { label: 'Total Sessions', value: '14,820', change: '+22.4%' },
                { label: 'Total Conversions', value: '384', change: '+31.8%' },
                { label: 'Conversion Rate', value: '2.59%', change: '+0.4%' },
                { label: 'Avg Order Value', value: '$128.50', change: '+$14.20' }
              ]
            },
            {
              slideNumber: 3,
              type: 'attribution',
              title: 'Channel Attribution & Traffic Mix',
              subtitle: 'Where qualified leads and traffic originated',
              trafficSources: [
                { source: 'Organic Google Search', percentage: 54 },
                { source: 'Direct Visitors', percentage: 22 },
                { source: 'Paid Meta & Google Ads', percentage: 16 },
                { source: 'Referral & Social', percentage: 8 }
              ]
            },
            {
              slideNumber: 4,
              type: 'insights',
              title: 'AI Strategic Intelligence & Diagnostics',
              subtitle: 'Automated trend diagnostics generated by ReportIQ AI',
              summary: 'Customer acquisition cost dropped 18% following landing page speed optimizations.',
              keyInsights: [
                'SEO non-branded organic clicks increased 38% after programmatic hub rollout',
                'Meta retargeting ROAS achieved 4.8x on top 3 creative variations',
                'Mobile checkout completion reached an all-time high of 71%'
              ]
            },
            {
              slideNumber: 5,
              type: 'actionPlan',
              title: 'Next Month Action Plan & Budget Approval',
              subtitle: 'Recommended growth priorities and budget allocation',
              actionItems: [
                'Expand high-intent Google Search campaigns for commercial keywords',
                'Launch automated abandoned cart recovery sequence on WhatsApp',
                'Implement A/B test on checkout order-bump offers'
              ],
              recommendedBudget: '$4,250'
            }
          ]
        });
      }
    } catch {
      // Fallback
    } finally {
      setLoading(false);
    }
  };

  if (!open) return null;

  const slides = deckData?.slides || [];
  const slide = slides[currentSlide] || {};
  const totalSlides = slides.length || 1;

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 99999,
        background: 'rgba(5, 7, 15, 0.96)',
        backdropFilter: 'blur(20px)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: isFullscreen ? 0 : 32,
      }}
    >
      {/* Deck Controls Header */}
      <div
        style={{
          width: '100%',
          maxWidth: isFullscreen ? '100%' : 1100,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 16,
          padding: '0 16px',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div
            style={{
              padding: '4px 12px',
              borderRadius: 20,
              background: 'rgba(138, 43, 226, 0.2)',
              border: '1px solid rgba(138, 43, 226, 0.4)',
              color: '#c084fc',
              fontSize: 12,
              fontWeight: 600,
            }}
          >
            AI Presentation Mode
          </div>
          <span style={{ color: '#94a3b8', fontSize: 13 }}>
            Slide {currentSlide + 1} of {totalSlides}
          </span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button
            onClick={() => setIsFullscreen(!isFullscreen)}
            style={{
              background: 'rgba(255, 255, 255, 0.08)',
              border: '1px solid rgba(255, 255, 255, 0.15)',
              color: '#e2e8f0',
              padding: '6px 12px',
              borderRadius: 8,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              fontSize: 13,
            }}
          >
            {isFullscreen ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
            {isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
          </button>
          <button
            onClick={onClose}
            style={{
              background: 'rgba(239, 68, 68, 0.15)',
              border: '1px solid rgba(239, 68, 68, 0.3)',
              color: '#f87171',
              padding: '6px 12px',
              borderRadius: 8,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              fontSize: 13,
            }}
          >
            <X size={16} /> Close Deck
          </button>
        </div>
      </div>

      {/* Main Slide Canvas (16:9 Aspect Ratio) */}
      <div
        style={{
          width: '100%',
          maxWidth: isFullscreen ? '96vw' : 1100,
          aspectRatio: '16/9',
          maxHeight: isFullscreen ? '85vh' : '72vh',
          background: 'linear-gradient(135deg, #0d1117 0%, #161b22 100%)',
          borderRadius: 20,
          border: '1px solid rgba(255, 255, 255, 0.12)',
          boxShadow: '0 30px 100px rgba(0, 0, 0, 0.8), 0 0 40px rgba(138, 43, 226, 0.25)',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          padding: '48px 56px',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        {/* Subtle background glowing orb */}
        <div
          style={{
            position: 'absolute',
            top: '-20%',
            right: '-10%',
            width: 450,
            height: 450,
            borderRadius: '50%',
            background: 'radial-gradient(circle, rgba(138,43,226,0.15) 0%, transparent 70%)',
            pointerEvents: 'none',
          }}
        />

        {/* Slide Content by Type */}
        {loading ? (
          <div style={{ textAlign: 'center', margin: 'auto', color: '#94a3b8' }}>Generating presentation slides...</div>
        ) : slide.type === 'cover' ? (
          <div style={{ margin: 'auto 0', maxWidth: 850 }}>
            <div
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                padding: '6px 14px',
                borderRadius: 20,
                background: 'rgba(0, 229, 255, 0.12)',
                color: '#22d3ee',
                fontSize: 13,
                fontWeight: 600,
                marginBottom: 24,
              }}
            >
              <Sparkles size={14} /> {slide.badge || 'ReportIQ Executive Deck'}
            </div>
            <h1
              style={{
                fontSize: '2.8rem',
                fontWeight: 800,
                color: '#ffffff',
                lineHeight: 1.2,
                marginBottom: 16,
                letterSpacing: '-0.02em',
              }}
            >
              {slide.title}
            </h1>
            <p style={{ fontSize: '1.25rem', color: '#94a3b8', marginBottom: 32 }}>
              {slide.subtitle}
            </p>
            <div
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 12,
                padding: '12px 20px',
                borderRadius: 12,
                background: 'rgba(255, 255, 255, 0.04)',
                border: '1px solid rgba(255, 255, 255, 0.08)',
                color: '#cbd5e1',
                fontSize: 14,
              }}
            >
              <ShieldCheck size={18} color="#10b981" />
              {slide.highlight || 'Verified Strategy Presentation'}
            </div>
          </div>
        ) : slide.type === 'metrics' ? (
          <div>
            <div style={{ marginBottom: 36 }}>
              <div style={{ color: '#c084fc', fontSize: 13, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 8 }}>
                Performance Overview
              </div>
              <h2 style={{ fontSize: '2.2rem', fontWeight: 800, color: '#fff' }}>{slide.title}</h2>
              <p style={{ color: '#94a3b8', fontSize: 15 }}>{slide.subtitle}</p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 20 }}>
              {slide.metrics?.map((m: any, i: number) => (
                <div
                  key={i}
                  style={{
                    padding: 24,
                    borderRadius: 16,
                    background: 'rgba(255, 255, 255, 0.04)',
                    border: '1px solid rgba(255, 255, 255, 0.08)',
                    boxShadow: '0 8px 24px rgba(0,0,0,0.2)',
                  }}
                >
                  <div style={{ color: '#94a3b8', fontSize: 13, marginBottom: 8 }}>{m.label}</div>
                  <div style={{ fontSize: '2rem', fontWeight: 800, color: '#fff', marginBottom: 8 }}>{m.value}</div>
                  <div style={{ display: 'inline-flex', alignItems: 'center', gap: 4, color: '#34d399', fontSize: 13, fontWeight: 600 }}>
                    <TrendingUp size={14} /> {m.change}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : slide.type === 'attribution' ? (
          <div>
            <div style={{ marginBottom: 36 }}>
              <div style={{ color: '#22d3ee', fontSize: 13, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 8 }}>
                Acquisition Channels
              </div>
              <h2 style={{ fontSize: '2.2rem', fontWeight: 800, color: '#fff' }}>{slide.title}</h2>
              <p style={{ color: '#94a3b8', fontSize: 15 }}>{slide.subtitle}</p>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
              {slide.trafficSources?.map((s: any, i: number) => (
                <div key={i}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6, fontSize: 14 }}>
                    <span style={{ color: '#f1f5f9', fontWeight: 500 }}>{s.source}</span>
                    <span style={{ color: '#22d3ee', fontWeight: 700 }}>{s.percentage}%</span>
                  </div>
                  <div style={{ width: '100%', height: 12, borderRadius: 6, background: 'rgba(255, 255, 255, 0.08)', overflow: 'hidden' }}>
                    <div
                      style={{
                        width: `${s.percentage}%`,
                        height: '100%',
                        borderRadius: 6,
                        background: 'linear-gradient(90deg, #8a2be2, #00e5ff)',
                        transition: 'width 0.8s ease',
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : slide.type === 'insights' ? (
          <div>
            <div style={{ marginBottom: 32 }}>
              <div style={{ color: '#f59e0b', fontSize: 13, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 8 }}>
                AI Analysis
              </div>
              <h2 style={{ fontSize: '2.2rem', fontWeight: 800, color: '#fff' }}>{slide.title}</h2>
              <p style={{ color: '#94a3b8', fontSize: 15 }}>{slide.subtitle}</p>
            </div>

            <div style={{ padding: 20, borderRadius: 12, background: 'rgba(245, 158, 11, 0.08)', border: '1px solid rgba(245, 158, 11, 0.25)', marginBottom: 24, color: '#fde68a', fontSize: 15, lineHeight: 1.6 }}>
              {slide.summary}
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              {slide.keyInsights?.map((insight: string, i: number) => (
                <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 12, color: '#e2e8f0', fontSize: 14 }}>
                  <CheckCircle size={18} color="#10b981" style={{ flexShrink: 0, marginTop: 2 }} />
                  <span>{insight}</span>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div>
            <div style={{ marginBottom: 32 }}>
              <div style={{ color: '#10b981', fontSize: 13, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 8 }}>
                Strategic Roadmap
              </div>
              <h2 style={{ fontSize: '2.2rem', fontWeight: 800, color: '#fff' }}>{slide.title}</h2>
              <p style={{ color: '#94a3b8', fontSize: 15 }}>{slide.subtitle}</p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: 32 }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                {slide.actionItems?.map((item: string, i: number) => (
                  <div
                    key={i}
                    style={{
                      padding: 16,
                      borderRadius: 12,
                      background: 'rgba(255, 255, 255, 0.04)',
                      border: '1px solid rgba(255, 255, 255, 0.08)',
                      display: 'flex',
                      alignItems: 'center',
                      gap: 12,
                      color: '#f8fafc',
                      fontSize: 14,
                    }}
                  >
                    <span style={{ width: 26, height: 26, borderRadius: '50%', background: 'rgba(16, 185, 129, 0.2)', color: '#34d399', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700, fontSize: 12 }}>
                      {i + 1}
                    </span>
                    {item}
                  </div>
                ))}
              </div>

              <div
                style={{
                  padding: 28,
                  borderRadius: 16,
                  background: 'linear-gradient(135deg, rgba(138,43,226,0.15) 0%, rgba(0,229,255,0.1) 100%)',
                  border: '1px solid rgba(138, 43, 226, 0.3)',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  alignItems: 'center',
                  textAlign: 'center',
                }}
              >
                <div style={{ color: '#cbd5e1', fontSize: 13, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 1 }}>Recommended Next Month Budget</div>
                <div style={{ fontSize: '2.8rem', fontWeight: 800, color: '#fff', marginBottom: 12 }}>{slide.recommendedBudget || '$4,500'}</div>
                <p style={{ color: '#94a3b8', fontSize: 12, lineHeight: 1.5 }}>
                  Projected ROI: 3.4x based on historical acquisition efficiency.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Slide Footer */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            borderTop: '1px solid rgba(255, 255, 255, 0.08)',
            paddingTop: 16,
            color: '#64748b',
            fontSize: 12,
          }}
        >
          <span>ReportIQ — Intelligent Client Reporting</span>
          <span>{deckData?.agencyName || 'Agency'} • Confidential Strategy Deck</span>
        </div>
      </div>

      {/* Navigation Controls Below Canvas */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 24,
          marginTop: 20,
        }}
      >
        <button
          onClick={() => setCurrentSlide((prev) => (prev > 0 ? prev - 1 : 0))}
          disabled={currentSlide === 0}
          style={{
            background: 'rgba(255, 255, 255, 0.08)',
            border: '1px solid rgba(255, 255, 255, 0.15)',
            color: currentSlide === 0 ? '#475569' : '#ffffff',
            padding: '10px 18px',
            borderRadius: 12,
            cursor: currentSlide === 0 ? 'not-allowed' : 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            fontSize: 14,
            fontWeight: 600,
          }}
        >
          <ChevronLeft size={18} /> Previous Slide
        </button>

        {/* Dots indicator */}
        <div style={{ display: 'flex', gap: 8 }}>
          {slides.map((_: any, idx: number) => (
            <button
              key={idx}
              onClick={() => setCurrentSlide(idx)}
              style={{
                width: idx === currentSlide ? 24 : 8,
                height: 8,
                borderRadius: 4,
                background: idx === currentSlide ? '#8a2be2' : 'rgba(255, 255, 255, 0.2)',
                border: 'none',
                cursor: 'pointer',
                transition: 'all 0.3s ease',
              }}
            />
          ))}
        </div>

        <button
          onClick={() => setCurrentSlide((prev) => (prev < totalSlides - 1 ? prev + 1 : prev))}
          disabled={currentSlide === totalSlides - 1}
          style={{
            background: 'linear-gradient(135deg, #8a2be2 0%, #00e5ff 100%)',
            border: 'none',
            color: '#ffffff',
            padding: '10px 22px',
            borderRadius: 12,
            cursor: currentSlide === totalSlides - 1 ? 'not-allowed' : 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            fontSize: 14,
            fontWeight: 600,
            opacity: currentSlide === totalSlides - 1 ? 0.4 : 1,
          }}
        >
          Next Slide <ChevronRight size={18} />
        </button>
      </div>
    </div>
  );
}
