import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Resend } from 'resend';

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  private resend: Resend | null = null;

  constructor(private config: ConfigService) {
    const apiKey = config.get('RESEND_API_KEY');
    if (apiKey && apiKey !== 're_your_resend_api_key') {
      this.resend = new Resend(apiKey);
      this.logger.log('Resend email service connected');
    } else {
      this.logger.warn('Resend API key not set — emails will be logged to console only');
    }
  }

  async sendReport({
    toEmail,
    toName,
    agencyName,
    agencyLogo,
    agencyColor,
    reportTitle,
    reportSlug,
    aiSummary,
    appUrl,
  }: {
    toEmail: string;
    toName: string;
    agencyName: string;
    agencyLogo?: string;
    agencyColor?: string;
    reportTitle: string;
    reportSlug: string;
    aiSummary: string;
    appUrl?: string;
  }) {
    const reportUrl = `${appUrl || this.config.get('FRONTEND_URL', 'http://localhost:3000')}/report/${reportSlug}`;
    const color = agencyColor || '#8a2be2';

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${reportTitle}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #0a0f1a; color: #f0f4f8; }
    .container { max-width: 600px; margin: 0 auto; padding: 40px 20px; }
    .header { text-align: center; padding: 40px 0 30px; border-bottom: 1px solid rgba(255,255,255,0.1); }
    .agency-name { font-size: 24px; font-weight: 700; color: ${color}; margin: 0; }
    .report-card { background: #121b2b; border: 1px solid rgba(255,255,255,0.1); border-radius: 16px; padding: 32px; margin: 32px 0; }
    .report-title { font-size: 22px; font-weight: 600; color: #fff; margin: 0 0 20px; }
    .ai-summary { font-size: 15px; line-height: 1.7; color: rgba(255,255,255,0.75); background: rgba(255,255,255,0.03); border-left: 3px solid ${color}; padding: 16px; border-radius: 0 8px 8px 0; margin: 20px 0; }
    .cta-btn { display: inline-block; background: ${color}; color: #fff; text-decoration: none; padding: 14px 32px; border-radius: 100px; font-weight: 600; font-size: 15px; margin: 20px 0; }
    .footer { text-align: center; color: rgba(255,255,255,0.3); font-size: 12px; padding-top: 32px; border-top: 1px solid rgba(255,255,255,0.06); }
    .footer a { color: rgba(255,255,255,0.4); text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      ${agencyLogo ? `<img src="${agencyLogo}" height="48" alt="${agencyName}" style="margin-bottom:12px;">` : ''}
      <p class="agency-name">${agencyName}</p>
    </div>

    <div class="report-card">
      <p style="font-size:12px;text-transform:uppercase;letter-spacing:0.1em;color:${color};margin:0 0 8px;">Performance Report Ready</p>
      <h2 class="report-title">Hi ${toName}, your report is ready! 📊</h2>
      <div class="ai-summary">${aiSummary}</div>
      <a href="${reportUrl}" class="cta-btn">View Full Report →</a>
    </div>

    <div class="footer">
      <p>This report was automatically generated by <a href="https://reportiq.app">ReportIQ</a> on behalf of ${agencyName}.</p>
      <p style="margin-top:8px;">Report Link: <a href="${reportUrl}">${reportUrl}</a></p>
    </div>
  </div>
</body>
</html>`;

    if (this.resend && this.config.get('USE_MOCK_EMAIL') !== 'true') {
      try {
        const result = await this.resend.emails.send({
          from: this.config.get('EMAIL_FROM', 'reports@reportiq.app'),
          to: toEmail,
          subject: `📊 ${reportTitle} — from ${agencyName}`,
          html,
        });
        this.logger.log(`Email sent to ${toEmail} — ID: ${result.data?.id}`);
        return { success: true, emailId: result.data?.id };
      } catch (error) {
        this.logger.error('Email send failed: ' + error.message);
        return { success: false, error: error.message };
      }
    } else {
      // Mock mode — log to console
      this.logger.log(`[MOCK EMAIL] To: ${toEmail} | Subject: ${reportTitle}`);
      this.logger.log(`[MOCK EMAIL] Report URL: ${reportUrl}`);
      return { success: true, mock: true, reportUrl };
    }
  }
}
